package com.followupnadlan.followuplog

data class FollowUpLogEntry(
    val actionType: FollowUpActionType,
    val timestampEpochMs: Long,
    val messagePreview: String,
    val phone: String = "",
    val source: String = ""
)

enum class FollowUpActionType {
    WHATSAPP_OPENED,
    SHARE_OPENED,
    COPY_USED,
    MISSED_CALL_DETECTED,
    WHATSAPP_REPLY_PREPARED,
    WHATSAPP_REPLY_OPENED,
    WHATSAPP_REPLY_FAILED,
    WHATSAPP_AUTO_SEND_ENABLED,
    WHATSAPP_AUTO_SEND_DISABLED,
    WHATSAPP_AUTO_SEND_ATTEMPTED,
    WHATSAPP_AUTO_SENT,
    WHATSAPP_AUTO_FAILED,
    WHATSAPP_ACCESSIBILITY_NOT_ENABLED,
    AUTO_SMS_SENT,
    AUTO_SMS_FAILED,
    FALLBACK_SMS_SENT,
    FALLBACK_SMS_OPENED,
    FALLBACK_SMS_FAILED,
    MANUAL_REPLY_PENDING,
    MANUAL_WHATSAPP_COMPOSER_OPENED,
    MANUAL_SMS_COMPOSER_OPENED,
    MANUAL_REPLY_CANCELLED,
    AUTO_SMS_SKIPPED_NO_PERMISSION,
    AUTO_SMS_SKIPPED_DISABLED,
    AUTO_SMS_SKIPPED_DUPLICATE,
    AUTO_SMS_SKIPPED_NO_NUMBER,
    AUTO_SMS_SKIPPED_EXCLUDED,
    AUTO_SMS_SKIPPED_BLOCKED_CONTACT,
    AUTO_SMS_SKIPPED_BLOCKED_NON_CONTACT,
    AUTO_SMS_SKIPPED_FIRST_TIME,
    AUTO_SMS_SKIPPED_CONTACT_TYPE_UNVERIFIED,
    AUTO_SMS_SKIPPED_CONTACTS_ONLY,
    AUTO_SMS_SKIPPED_NOT_ALLOWED,
    AUTO_SMS_SKIPPED_OUTSIDE_WORKING_HOURS,
    MANUAL_REPLY_OPENED,
    CONTACT_CARD_OPENED,
    WHATSAPP_NUMBER_NOT_ON_WHATSAPP
}
